apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
