apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-media-config
  namespace: ecommerce
data:
  default.conf: |
    server {
        listen 80;

        location /media/ {
            alias /app/media/;
        }

        location / {
            proxy_pass http://django;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
