apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}

          command:
        
            - gunicorn
            - config.wsgi:application 
            - --bind
            - 0.0.0.0:8000

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 5


          envFrom:
            - secretRef:
                name: django-secret    
          env:
            
            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.env.DJANGO_SETTINGS_MODULE }}"
            
            - name: ALLOWED_HOSTS
              value: "{{ .Values.env.ALLOWED_HOSTS }}"
            

          volumeMounts:
            - name: media-volume
              mountPath: /app/media

      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: django-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
