apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: ecommerce

  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - sh
            - -c
            - |
              python manage.py migrate

          envFrom:
            - secretRef:
                name: django-secret

          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "{{ .Values.env.DJANGO_SETTINGS_MODULE }}"
            - name: ALLOWED_HOSTS
              value: "{{ .Values.env.ALLOWED_HOSTS }}"
