apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: ecommerce
type: Opaque
stringData:
  SECRET_KEY: supersecretkey
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/django_ecommerce
  REDIS_URL: redis://redis:6379/0

  
  AWS_STORAGE_BUCKET_NAME: sohail-django-media-2026-001
  AWS_S3_REGION_NAME: ap-south-1
